"""add_preview_session_fields

Revision ID: 29ca809015cb
Revises: 563d9c23867f
Create Date: 2026-04-21 12:27:43.793743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ca809015cb'
down_revision: Union[str, Sequence[str], None] = '563d9c23867f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_runtime_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('container_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('preview_port', sa.Integer(), nullable=True),
    sa.Column('frontend_port', sa.Integer(), nullable=True),
    sa.Column('backend_port', sa.Integer(), nullable=True),
    sa.Column('preview_session_key', sa.String(), nullable=True),
    sa.Column('preview_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frontend_status', sa.String(), nullable=True),
    sa.Column('backend_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_workspace_runtime_sessions_user_project')
    )
    op.create_index(op.f('ix_workspace_runtime_sessions_id'), 'workspace_runtime_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_runtime_sessions_preview_session_key'), 'workspace_runtime_sessions', ['preview_session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_runtime_sessions_preview_session_key'), table_name='workspace_runtime_sessions')
    op.drop_index(op.f('ix_workspace_runtime_sessions_id'), table_name='workspace_runtime_sessions')
    op.drop_table('workspace_runtime_sessions')
    # ### end Alembic commands ###